### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/NIPT#118]
The FF tab in the NIPT viewer does not work. Produces a "internal server error" message. Seems to influence all batches.

**Comment by mayabrandi** [comment]
Okej. Ill have a look tomorrow.

/Maya

**Comment by mayabrandi** [comment]
The issue is that recently the value <1 has started to come in to the FF column in the database. The issue was brought up earlier by Maria (CCd). 
It can be handled in the code by automatically replacing <1 with 1 or something. But I have been waiting for Maria to discuss this with the NIPT-experts. I can go in to the database and manually fix the samples that have FF <1 if you want me to. But we need a more sustainable solution of course :) Waiting for reply from Maria!

Best regards,

Maya

**Comment by mayabrandi** [comment]
Hi Maya,

Sorry, I had totally forgotten about this. We have now discussed it. Is it possible to by default automatically set all the values that are <1 to 0 instead from now on? That would be the best solution.

Best regards
Maria

Maria Pettersson | MSc PhD
Associate clinical laboratory geneticist, Clinical Genetics Unit L5:03
Karolinska University Hospital Solna
Sweden

Från: Maya Brandi <maya.brandi@scilifelab.se>
Skickat: den 29 januari 2020 14:03
Till: Clinical-Genomics/NIPT <reply@reply.github.com>; Maria Pettersson <maria.pettersson.1@ki.se>
Kopia: Clinical-Genomics/NIPT <NIPT@noreply.github.com>; Subscribed <subscribed@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Internal server error (#118)

The issue is that recently the value <1 has started to come in to the FF column in the database. The issue was brought up earlier by Maria (CCd).
It can be handled in the code by automatically replacing <1 with 1 or something. But I have been waiting for Maria to discuss this with the NIPT-experts. I can go in to the database and manually fix the samples that have FF <1 if you want me to. But we need a more sustainable solution of course :) Waiting for reply from Maria!

Best regards,

Maya



28 jan. 2020 kl. 11:51 skrev AnnHam <notifications@github.com<mailto:notifications@github.com>>:

The FF tab in the NIPT viewer does not work. Produces a "internal server error" message. Seems to influence all batches.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2FNIPT%2Fissues%2F118%3Femail_source%3Dnotifications%26email_token%3DAAJ65XPZTNYAQX2LEJGFHT3RAAE4TA5CNFSM4KMQJHKKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IJF3FOA&data=02%7C01%7Cmaria.pettersson.1%40ki.se%7C57a5a655977e4038120308d7a4bb8ac1%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637158997718504237&sdata=5FKlVqHyOZayMOX0MFF7GR%2Bj2Da3uwZceXI4y187pLQ%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAJ65XKV5LEWFE3JE4PHF2LRAAE4TANCNFSM4KMQJHKA&data=02%7C01%7Cmaria.pettersson.1%40ki.se%7C57a5a655977e4038120308d7a4bb8ac1%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637158997718504237&sdata=jPXMat1iTzK7p3LozIMVEj%2FjMgzbeA7fPqgy5LUDILs%3D&reserved=0>.




När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by mayabrandi** [comment]
Yep! No problem. Ill do it manually for the once that are already in the database right now. And ill update the code for it tomorrow or on monday. If the error occurs again, its probably because I didn’t get time to fix it before new samples were loaded. Hopefully that will not happen. But if it does, just email me. 

Ill let you know when the code is updated.

Best,

maya

**Comment by mayabrandi** [comment]
Excellent, thank you so much Maya!

Best regards
Maria

Maria Pettersson | MSc PhD
Associate clinical laboratory geneticist, Clinical Genetics Unit L5:03
Karolinska University Hospital Solna
Sweden

Från: Maya Brandi <maya.brandi@scilifelab.se>
Skickat: den 29 januari 2020 14:24
Till: Maria Pettersson <maria.pettersson.1@ki.se>
Kopia: Clinical-Genomics/NIPT <reply@reply.github.com>; Clinical-Genomics/NIPT <NIPT@noreply.github.com>; Subscribed <subscribed@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Internal server error (#118)

Yep! No problem. Ill do it manually for the once that are already in the database right now. And ill update the code for it tomorrow or on monday. If the error occurs again, its probably because I didn’t get time to fix it before new samples were loaded. Hopefully that will not happen. But if it does, just email me.

Ill let you know when the code is updated.

Best,

maya


29 jan. 2020 kl. 14:20 skrev Maria Pettersson <maria.pettersson.1@ki.se<mailto:maria.pettersson.1@ki.se>>:

Hi Maya,

Sorry, I had totally forgotten about this. We have now discussed it. Is it possible to by default automatically set all the values that are <1 to 0 instead from now on? That would be the best solution.

Best regards
Maria

Maria Pettersson | MSc PhD
Associate clinical laboratory geneticist, Clinical Genetics Unit L5:03
Karolinska University Hospital Solna
Sweden

Från: Maya Brandi <maya.brandi@scilifelab.se<mailto:maya.brandi@scilifelab.se>>
Skickat: den 29 januari 2020 14:03
Till: Clinical-Genomics/NIPT <reply@reply.github.com<mailto:reply@reply.github.com>>; Maria Pettersson <maria.pettersson.1@ki.se<mailto:maria.pettersson.1@ki.se>>
Kopia: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>; Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Ämne: Re: [Clinical-Genomics/NIPT] Internal server error (#118)

The issue is that recently the value <1 has started to come in to the FF column in the database. The issue was brought up earlier by Maria (CCd).
It can be handled in the code by automatically replacing <1 with 1 or something. But I have been waiting for Maria to discuss this with the NIPT-experts. I can go in to the database and manually fix the samples that have FF <1 if you want me to. But we need a more sustainable solution of course :) Waiting for reply from Maria!

Best regards,

Maya




28 jan. 2020 kl. 11:51 skrev AnnHam <notifications@github.com<mailto:notifications@github.com>>:

The FF tab in the NIPT viewer does not work. Produces a "internal server error" message. Seems to influence all batches.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2FNIPT%2Fissues%2F118%3Femail_source%3Dnotifications%26email_token%3DAAJ65XPZTNYAQX2LEJGFHT3RAAE4TA5CNFSM4KMQJHKKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IJF3FOA&data=02%7C01%7Cmaria.pettersson.1%40ki.se%7C267d9321f5b74b597e8808d7a4be7980%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637159010938243425&sdata=BxkH3ICKOu3GF3Pm0YBgzrw35ktnPEQCt9RRgaFpNzk%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAJ65XKV5LEWFE3JE4PHF2LRAAE4TANCNFSM4KMQJHKA&data=02%7C01%7Cmaria.pettersson.1%40ki.se%7C267d9321f5b74b597e8808d7a4be7980%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637159010938253423&sdata=tz3WxGNzgh7YGj0eD3iWRgWoj5cE%2F4C3gBanatrao78%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fki.se%2Fmedarbetare%2Fintegritetsskyddspolicy&data=02%7C01%7Cmaria.pettersson.1%40ki.se%7C267d9321f5b74b597e8808d7a4be7980%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637159010938253423&sdata=GdVakBsl%2BVZsl9JVqsqrX7k59679ghHMQu3Z1QTLW9Y%3D&reserved=0>.

Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by mayabrandi** [comment]
The plots are now visible again.

**Comment by mayabrandi** [comment]
I have now updated the code  (<1% is now being translated to 1%). The problem should not appear again.

Best,

Maya
