### ISSUE TITLE
incorrect samples in the VALID batches

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#14]
The batches that are marked VALID (e.g. 1624488_955432) contains a sample with incorrect data due to changed file info?

**Comment by mayabrandi** [comment]
Ill have to look into this, but consider it as low priority. Is that correct @alieden? 

Best,

Maya

**Comment by mayabrandi** [comment]
All samples come from the NIPT analysis result files. These incorect samples are generated because some files have tis extra row with contet that look like this:

"# Disclosure: The VeriSeq NIPT Analysis Software (16 Sample) is CE-marked in accordance with the IVD Directive 98/79/EC.",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

I didnt see this before, and I don't know why its there. I can create exceptions for this kind of lines, but I dont like exceptions, and probably better to handle it earlier in the pipeline? @ingkebil, do you know why we have this extra row in some of the NIPT result files?

**Comment by ingkebil** [comment]
This is a comment added after the upgrade of the NIPT software beginning of May and should be ignored. There is no way to exclude this line from appearing in the result file.

**Comment by mayabrandi** [comment]
Ill ignore the lines beginning with #. A real sample line will never begin with # I guess.

**Comment by ingkebil** [comment]
Sounds about right. Convention would dictate lines starting with `#` are coments, so your suggestion is a good idea.

**Comment by mayabrandi** [comment]
I have now changed the code to ignore these lines. This implies that samples with sample names beginning with # also will be ignored, since the first entry on a line is the sample name. Agne, you might want to document this at some place. @alieden

**Comment by mayabrandi** [comment]
Im not sure if im allowed to delete old batches that have the incorrect samples. I have to do this, to be able to update them without the incorregt samples. Should I do that @alieden? Or you want me to leve the old batches as they are?

Best,

M

**Comment by alieden** [comment]
OO to delete baches if you have to replace them with corrected info. However, I would be grateful if you could let me know for what batches you do this so that I can go back and classifiy etc

**Comment by mayabrandi** [comment]
The following batches are now updated to not contain the "incorrect sample".

1624512_851133VALID, 1624488_955432VALID, 1624431_533898VALID, 1624233_589794VALID
