### ISSUE TITLE
Enhancement (not acute) - Extra dots in the graphs?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#30]
If you look at the T21 graph for example (present in other graphs also) you see that there are some extra dots in the graph above the threshold (a couple of them are marked by arrows in the attached image).
 I'm not sure why these appear and they are a bit confusing I think, looks like negative samples with very high NCV-values?

![extra_dots](https://cloud.githubusercontent.com/assets/22740092/20245395/ce7e04c2-a9a0-11e6-94d0-cda797172d4c.png)

**Comment by mayabrandi** [comment]
Yes. What is negative (before we called these validation samples, but you decided to call them negative) in the graph are ALL prior samples that were marked to be "included".  Some of these are then classified by you to be eg verified, fp, etc these are plotted slightly to the right of the negative. You (or maybe Ellika) asked me to do this so that it would be easier to see the different classes. If all are plotted on the same point on the x-axes, it's probably less confusing, but harder to separate the classes. 

Vänligen,
Maya Brandi

**Comment by alieden** [comment]
I thought we had been through all batches and checked all samples that should be included and in the process removed all samples from the validation study? The idea is now to only show (in all graphs) samples that have gone through clinical runs (and checked to be included to remove duplicates). Since we now have so much more clinical samples, and they are the ones we want to calculate stats on, the validation samples should not be included.

**Comment by mayabrandi** [comment]
I dont know witch samples you have marked to be "included" and not. 

Only samples that have been marked "included" are shown in the graps. If you have marked all samples from validation-batches not to be included, then they are not in the graphs. 

Nothing is removed from the database. If you want me to remove batches, you need to give me a list of the run ids of these batches.

**Comment by alieden** [comment]
I'm sorry I don't get want you mean here obviously. 

Let's use the the example of the top suspected NCV21 value (about 25). On the left hand side of this sample (2015-15818) there is a greyish dot that is not showing any info when you hover over it? What is this dot representing?

**Comment by alieden** [comment]
Are you saying that all samples that are shifted to the right compared to verified for clarity (i.e. false positive and suspected) have an extra dot? If so can we get rid of the extra dots please?

**Comment by mayabrandi** [comment]
Will be handeled by solving issue #12
