### ISSUE TITLE
Waning -  Compare NCVY with ff

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/NIPT#90]
Hej,
 
Graferna med ff vs NCVY eller NCVX som vi lagt till behöver ju i huvudsak bara analyseras av lab vid två tillfällen enligt tidigare info.
 
1.       Om ett XY-prov har ett lågt NCVY värde (mellan 20 och 50) kontrolleras detta mot förväntad ff (ett prediktionsintervall med 4,5 SD) för att undvika att ett XX-prov blir klassat som XY pga förhöjd en ”bakgrundssignal” för Y.
2.       Om ett XY-prov hamnar till vänster om XY-klustret i NCVY vs NCVX grafen beror det mest sannolikt pga av maternell X0 mosaicism i blodet. Vid detta resultat kontrolleras NCVY och NCVX mot estimerad ff. Om NCVY faller inom prediktionsintervallet för ff samtidigt som NCVX är lågt så finns det ej något tydligt stöd för X0/XY mosaicism hos fostret och analysen besvaras som normal XY.

För den sista varianten så märker ju labbet detta när man analyserar redan nu men för det första måste man antingen rutinmässigt analysera alla batcher (lite onödigt) eller manuellt titta i tabellen efter värden för NCVY som ligger mellan 20 och 50.
 
Min fundering är därför om man skulle kunna lägga till en flaggning avseende detta i NCV Table dvs om NCVY är större/lika med 20 men mindre än 50 så dyker det upp en text ”Compare NCVY with ff” i Warning kolumnen för det provet? Är det mkt jobb eller något som du skulle kunna fixa snabbt?
 
Mvh,
 
Agne

**Comment by mayabrandi** [comment]
Fixed now. See eg https://nipt.scilifelab.se/NIPT/batches/AHT3LKADXX/ 
Non of the current batches with 20<=NCVY<50, have FF data in the database. So the FF fraction plots for these batches are empty. I suppose this is because the batches are old...?

**Comment by alieden** [comment]
Kontrollerade två batcher (# nedan) med ett prov i det aktuella spannet. Ser bra ut!


1737295_454818
1621170_658138



Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 28 maj 2018 08:20
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Waning - Compare NCVY with ff (#90)


Fixed now. See eg https://nipt.scilifelab.se/NIPT/batches/AHT3LKADXX/
Non of the current batches with 20<=NCVY<50, have FF data in the database. So the FF fraction plots for these batches are empty. I suppose this is because the batches are old...? @alieden<https://github.com/alieden>
